In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import load_boston, load_iris
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression,Ridge, SGDRegressor
from sklearn.neural_network import MLPRegressor # 딥러닝 neural_network
from sklearn.metrics import r2_score# 선형 모델(Linear Models)

import mglearn
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family']='Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False

import warnings
warnings.simplefilter('ignore')

In [2]:
'''
1. total_grade.csv (q1,q2,mtot,ftot, finalscore)
를 학습하여
q1:824, q2:910, mtot:2345612, ftot:1090인경우
final score 를 예측하시요
(linearRegress, SGDRegressor, MLPRegressor
각각의 train, test , r2 스코어를 구하시요.)
'''

'\n1. total_grade.csv (q1,q2,mtot,ftot, finalscore)\n를 학습하여\nq1:824, q2:910, mtot:2345612, ftot:1090인경우\nfinal score 를 예측하시요\n(linearRegress, SGDRegressor, MLPRegressor\n각각의 train, test , r2 스코어를 구하시요.)\n'

In [3]:
gradeDF = pd.read_csv( '../../data/total_grade.csv')
gradeDF.columns =['q1','q2','mtot','ftot','finalscore']
gradeDF.head()

q1     q2       mtot    ftot  finalscore
0  828.0  920.0  1234567.0  1020.0      1111.0
1  824.0  910.0  2345612.0  1090.0      1234.0
2  880.0  900.0  3456123.0  1010.0      1000.0
3  870.0  990.0  2312123.0  1001.0      1122.0
4  860.0  980.0  3223123.0  1008.0      1133.0

In [4]:
# 특성데이터 추출
gr_x_data = gradeDF[['q1','q2','mtot','ftot']]
gr_x_data

q1     q2       mtot    ftot
0  828.0  920.0  1234567.0  1020.0
1  824.0  910.0  2345612.0  1090.0
2  880.0  900.0  3456123.0  1010.0
3  870.0  990.0  2312123.0  1001.0
4  860.0  980.0  3223123.0  1008.0
5  850.0  970.0  2432123.0  1100.0

In [5]:
# 라벨데이터 추출
gr_y_data = gradeDF['finalscore']
gr_y_data

0    1111.0
1    1234.0
2    1000.0
3    1122.0
4    1133.0
5    1221.0
Name: finalscore, dtype: float64

### 데이터 정규화

In [6]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [7]:
scaleX = StandardScaler()
x_dataS = scaleX.fit_transform(gr_x_data)

In [8]:
x_dataS.shape

(6, 4)

In [9]:
# 입력값 정규화
xx = scaleX.transform( [[824,910,2345612,1090]] )

### train test 데이터 나누기

In [10]:
x_train, x_test, y_train, y_test=train_test_split(x_dataS, gr_y_data, test_size=0.2, random_state=1)

## LinearRegression()

In [11]:
model_lr = LinearRegression()
model_lr.fit(gr_x_data,gr_y_data)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
# 각 변수에 대한 기울기 
model_lr.coef_

array([-2.54313540e+00,  1.19754005e+00,  2.08691422e-05,  1.02641452e+00])

In [13]:
# b
model_lr.intercept_

1054.1343924649852

In [14]:
model_lr.predict(xx)

array([1057.73988287])

In [15]:
# R2 스코어 확인
print('훈련데이터 R2 : ',model_lr.score(x_train, y_train))
print('테스트데이터 R2 : ',model_lr.score(x_test, y_test))

훈련데이터 R2 :  -4.421273995233581
테스트데이터 R2 :  -0.22054396832988532


## SGDRegressor()

In [16]:
modelSGD = SGDRegressor(max_iter=5000, alpha=0.0001,
                         early_stopping= True)
modelSGD.fit(x_train,y_train)

SGDRegressor(alpha=0.0001, average=False, early_stopping=True, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=5000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [17]:
# 예측값
modelSGD.predict(xx)

array([848.79791015])

In [18]:
# R2 스코어 확인
print('훈련데이터 R2 : ',modelSGD.score(x_train, y_train))
print('테스트데이터 R2 : ',modelSGD.score(x_test, y_test))

훈련데이터 R2 :  -2.5609116435077683
테스트데이터 R2 :  -37.00571459241146


## MLPRegressor()

In [19]:
modelNN = MLPRegressor(max_iter=5000, alpha=0.001,
                        solver='adam',
                         hidden_layer_sizes= (100,10))
modelNN.fit(x_train, y_train)

MLPRegressor(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100, 10), learning_rate='constant',
             learning_rate_init=0.001, max_iter=5000, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=None, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [20]:
# 예측값
modelNN.predict(xx)

array([634.78571293])

In [21]:
# R2 스코어 확인
print('훈련데이터 R2 : ',modelNN.score(x_train, y_train))
print('테스트데이터 R2 : ',modelNN.score(x_test, y_test))

훈련데이터 R2 :  0.999992278600427
테스트데이터 R2 :  -16.72724780316613


In [22]:
'''
2. trees.csv를 읽어들여서 아래에 대해
linearRegress, SGDRegressor, MLPRegressor
각각의 train, test , r2 스코어를 구하고
아래의 Volume을 예측하시요.
Girth 8.8, 10.5
Height 63, 72
'''

'\n2. trees.csv를 읽어들여서 아래에 대해\nlinearRegress, SGDRegressor, MLPRegressor\n각각의 train, test , r2 스코어를 구하고\n아래의 Volume을 예측하시요.\nGirth 8.8, 10.5\nHeight 63, 72\n'

In [23]:
treesDF = pd.read_csv( '../../data/trees.csv')
treesDF.head()

Girth  Height  Volume
0    8.3      70    10.3
1    8.6      65    10.3
2    8.8      63    10.2
3   10.5      72    16.4
4   10.7      81    18.8

In [24]:
# 특성데이터 추출
tr_x_data = treesDF[['Girth','Height']]
tr_x_data.head()

Girth  Height
0    8.3      70
1    8.6      65
2    8.8      63
3   10.5      72
4   10.7      81

In [25]:
# 라벨데이터 추출
tr_y_data = treesDF['Volume']
tr_y_data.head()

0    10.3
1    10.3
2    10.2
3    16.4
4    18.8
Name: Volume, dtype: float64

### 데이터 정규화

In [26]:
scaleX = StandardScaler()
x_dataT = scaleX.fit_transform(tr_x_data)

In [27]:
# 입력값 정규화
yy = scaleX.transform([[8.8,63],[10.5,72]])

### 데이터나누기

In [28]:
# 정규화된 데이터
x_train, x_test, y_train, y_test=train_test_split(x_dataT, tr_y_data, test_size=0.2, random_state=1)

## LinearRegression()

In [29]:
tr_model_lr = LinearRegression()
tr_model_lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
# R2 스코어 확인
print('훈련데이터 R2 : ',tr_model_lr.score(x_train, y_train))
print('테스트데이터 R2 : ',tr_model_lr.score(x_test, y_test))

훈련데이터 R2 :  0.9501000553451436
테스트데이터 R2 :  0.9161318541491206


In [31]:
# 예측값
tr_model_lr.predict(yy)

array([ 5.84983575, 16.27579072])

## SGDRegressor()

In [32]:
tr_modelSGD = SGDRegressor(max_iter=5000, alpha=0.0001,
                         early_stopping= True)
tr_modelSGD.fit(x_train,y_train)

SGDRegressor(alpha=0.0001, average=False, early_stopping=True, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=5000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [33]:
# R2 스코어 확인
print('훈련데이터 R2 : ',tr_modelSGD.score(x_train, y_train))
print('테스트데이터 R2 : ',tr_modelSGD.score(x_test, y_test))

훈련데이터 R2 :  0.9179948586526562
테스트데이터 R2 :  0.8773970811055487


In [34]:
tr_modelSGD.predict(yy)

array([ 1.05176976, 13.98904003])

## MLPRegressor()

In [35]:
tr_modelNN = MLPRegressor(max_iter=5000, alpha=0.001,
                        solver='adam',
                         hidden_layer_sizes= (100,10))
tr_modelNN.fit(x_train, y_train)

MLPRegressor(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100, 10), learning_rate='constant',
             learning_rate_init=0.001, max_iter=5000, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=None, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [36]:
print('훈련데이터 R2 : ',tr_modelNN.score(x_train, y_train))
print('테스트데이터 R2 : ',tr_modelNN.score(x_test, y_test))

훈련데이터 R2 :  0.9845391282881463
테스트데이터 R2 :  0.9219108293276757


In [37]:
tr_modelSGD.predict(yy)

array([ 1.05176976, 13.98904003])

In [38]:
'''
3. volume이 40 이상이면 크다
30이상이면 보통 미만이면 적음으로
아래와 같이 출력하시요
volume  정도
============
 10.3    적음
...

'''

'\n3. volume이 40 이상이면 크다\n30이상이면 보통 미만이면 적음으로\n아래와 같이 출력하시요\nvolume  정도\n============\n 10.3    적음\n...\n\n'

In [39]:
treesDF['Volume'].values

array([10.3, 10.3, 10.2, 16.4, 18.8, 19.7, 15.6, 18.2, 22.6, 19.9, 24.2,
       21. , 21.4, 21.3, 19.1, 22.2, 33.8, 27.4, 25.7, 24.9, 34.5, 31.7,
       36.3, 38.3, 42.6, 55.4, 55.7, 58.3, 51.5, 51. , 77. ])

In [40]:
treesDF['정도']=treesDF['Volume'].map(lambda x : '크다' if x>=40 else '보통' if x>=30 else '작다')

In [41]:
treesDF.head()

Girth  Height  Volume  정도
0    8.3      70    10.3  작다
1    8.6      65    10.3  작다
2    8.8      63    10.2  작다
3   10.5      72    16.4  작다
4   10.7      81    18.8  작다

In [42]:
'''
4. Height  가 가장 작은값과 큰값을
구하시요
'''

'\n4. Height  가 가장 작은값과 큰값을\n구하시요\n'

In [43]:
print(treesDF['Height'].max(),treesDF['Height'].min())

87 63


In [44]:
'''
5. girth(테두리) 가 가장큰 top5를
출력하세요(girth, height, volume)
'''

'\n5. girth(테두리) 가 가장큰 top5를\n출력하세요(girth, height, volume)\n'

In [45]:
treesDF.sort_values('Girth',ascending=False).head()

Girth  Height  Volume  정도
30   20.6      87    77.0  크다
29   18.0      80    51.0  크다
28   18.0      80    51.5  크다
27   17.9      80    58.3  크다
26   17.5      82    55.7  크다