In [2]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import sklearn.metrics as metrics

from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.pipeline import make_pipeline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [3]:
'''
정보 1 : 과거 임신 횟수 (pregnant)
정보 2 : 포도당 부하 검사 2시간 후 공복 혈당 농도 (plasma)
정보 3 : 확장기 혈압 (pressure)
정보 4 : 삼두근 피부 주름 두께 (thickness)
정보 5 : 혈정 인슐린 (insulin)
정보 6 : 체질량 지수 (BMI)
정보 7 : 당뇨병 가족력 (pedigree)
정보 8 : 나이 (age)

클래스 : 당뇨( 1) , 당뇨가 아님 ( 0 )
'''


'\n정보 1 : 과거 임신 횟수 (pregnant)\n정보 2 : 포도당 부하 검사 2시간 후 공복 혈당 농도 (plasma)\n정보 3 : 확장기 혈압 (pressure)\n정보 4 : 삼두근 피부 주름 두께 (thickness)\n정보 5 : 혈정 인슐린 (insulin)\n정보 6 : 체질량 지수 (BMI)\n정보 7 : 당뇨병 가족력 (pedigree)\n정보 8 : 나이 (age)\n\n클래스 : 당뇨( 1) , 당뇨가 아님 ( 0 )\n'

## (피마인디안) 연습문제

In [4]:
df = pd.read_csv('../../data/pima-indians-diabetes.data.csv')
df.head(3)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1

In [5]:
'''
# train , test  셋으로 나눈후
# 각각의 정확도를 구하시요.
# test셋의 0번제 row 데이터로 당뇨병 유무를 확인하시요..
'''

'\n# train , test  셋으로 나눈후\n# 각각의 정확도를 구하시요.\n# test셋의 0번제 row 데이터로 당뇨병 유무를 확인하시요..\n'

### 1. 특성 데이터와 라벨 데이터 구분

In [6]:
x_data = df.iloc[:,:-1]
y_data = df.iloc[:,-1]

print(x_data.shape, y_data.shape)

(768, 8) (768,)


In [7]:
x_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [8]:
y_data.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

### 데이터 셋 구분

In [9]:
x_train, x_test, y_train, y_test=train_test_split(x_data, y_data, test_size=0.2, random_state=1)

In [10]:
print(x_train.shape,y_train.shape)

(614, 8) (614,)


### 2. 각각의 정확도를 구하시요.

In [11]:
model_logi =  make_pipeline(StandardScaler(),LogisticRegression())
model_logi.fit(x_data, y_data)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('logisticregression',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [12]:
## accuracy (정확도) 참고
print(model_logi.score(x_train, y_train))
print(model_logi.score(x_test, y_test))

0.7850162866449512
0.7792207792207793


### 3. test셋의 0번째 row 데이터로 당뇨병 유무를 확인하시요..

In [24]:
x= np.array([x_test.iloc[0].values])
x

array([[  7.   , 136.   ,  74.   ,  26.   , 135.   ,  26.   ,   0.647,
         51.   ]])

In [14]:
model_logi.predict_proba(x)

array([[0.54566133, 0.45433867]])

In [15]:
model_logi.predict(x)

array([0], dtype=int64)